// Generated by CoffeeScript 1.10.0
(function() {
  var blessed, createInput;

  blessed = require('blessed');

  createInput = function(form, label, name, top) {
    blessed.box({
      parent: form,
      height: 1,
      width: 5,
      align: 'left',
      content: label,
      top: top,
      left: 0,
      style: {
        bg: 'blue',
        fg: 'white'
      }
    });
    return blessed.textbox({
      parent: form,
      name: name,
      mouse: true,
      keys: true,
      inputOnFocus: true,
      height: 1,
      width: 20,
      top: top,
      left: 5,
      style: {
        bg: 'white',
        fg: 'black'
      }
    });
  };

  module.exports = function(screen) {
    var form, host, name, port, submit, user;
    form = blessed.form({
      screen: screen,
      parent: screen,
      border: 'line',
      hidden: true,
      width: 27,
      height: 11,
      top: 'center',
      left: 'center',
      label: 'Add record',
      keys: true,
      mouse: true,
      vi: true,
      style: {
        bg: 'blue',
        border: {
          bg: 'blue',
          fg: 'white'
        },
        label: {
          bg: 'blue',
          bold: true
        }
      }
    });
    name = createInput(form, 'Name', 'name', 0);
    host = createInput(form, 'Host', 'host', 2);
    user = createInput(form, 'User', 'user', 4);
    port = createInput(form, 'Port', 'port', 6);
    submit = blessed.button({
      parent: form,
      name: 'submit',
      mouse: true,
      keys: true,
      height: 1,
      width: 'shrink',
      left: 'center',
      top: 8,
      content: 'Submit',
      style: {
        fg: 'white',
        bg: 'green',
        focus: {
          bg: 'red'
        }
      }
    });
    form.toggle = function() {
      if (this.hidden) {
        this.screen.saveFocus();
        this.reset();
        this.show();
        this.setFront();
        this.focusFirst();
      } else {
        this.hide();
        this.screen.restoreFocus();
      }
      return this.screen.render();
    };
    submit.on('press', function() {
      return form.submit();
    });
    form.on('submit', function() {
      return form.toggle();
    });
    form.on('cancel', function() {
      return form.toggle();
    });
    return form;
  };

}).call(this);
